### ISSUE TITLE
Repo out of sync from upstream

### ISSUE THREAD

**Issue by jlaffaye** [tyjak/vim-redact-pass#1]
This GitHub clone is missing:

- https://dev.sanctum.geek.nz/cgit/vim-redact-pass.git/commit/?id=dee138eb8060ce2133606e4c8e85776132c61c95
- https://dev.sanctum.geek.nz/cgit/vim-redact-pass.git/commit/?id=93869ba533b89cc23378a8ae76c170ba8fc224d5

**Comment by tyjak** [comment]
Hi, thank you  for your comment, it is sync now.
